### ISSUE TITLE
⚠️  Potential data loss within a working dir when using an argument `.` for the `dest_path` in `convert` function

### ISSUE THREAD

**Issue by sbamin** [cytomining/CytoTable#102]
I have not throughly tested CytoTable but I was just doing an install in docker env. I am yet to debug this but looks like I am unable to recover source path (directory and its recursive contents) if I follow `convert` function per [tutorial](https://cytomining.github.io/CytoTable/tutorial.html).

1. Create a docker instance:

```sh
mkdir -p ~/dev && cd ~/dev
docker pull python:3.10.11
mkdir tmp
docker run -it -v tmp:/scratch python:3.10.11 /bin/bash
```

2. Within a docker container:

```sh
## install CytoTable
pip install git+https://github.com/cytomining/CytoTable.git
```

>Successfully built CytoTable
Installing collected packages: duckdb, urllib3, typing-extensions, typeguard, tblib, six, setproctitle, pyzmq, pyjwt, pycparser, pyasn1, psutil, protobuf, numpy, jmespath, idna, google-crc32c, dill, cloudpathlib, charset-normalizer, certifi, cachetools, bcrypt, rsa, requests, python-dateutil, pyasn1-modules, pyarrow, isodate, googleapis-common-protos, google-resumable-media, cffi, pynacl, google-auth, cryptography, botocore, azure-core, s3transfer, paramiko, google-api-core, azure-storage-blob, google-cloud-core, globus-sdk, boto3, parsl, google-cloud-storage, CytoTable
Successfully installed CytoTable-0.0.1 azure-core-1.29.4 azure-storage-blob-12.18.0 bcrypt-4.0.1 boto3-1.28.46 botocore-1.31.46 cachetools-5.3.1 certifi-2023.7.22 cffi-1.15.1 charset-normalizer-3.2.0 cloudpathlib-0.13.0 cryptography-41.0.3 dill-0.3.7 duckdb-0.8.1 globus-sdk-3.28.0 google-api-core-2.11.1 google-auth-2.23.0 google-cloud-core-2.3.3 google-cloud-storage-2.10.0 google-crc32c-1.5.0 google-resumable-media-2.6.0 googleapis-common-protos-1.60.0 idna-3.4 isodate-0.6.1 jmespath-1.0.1 numpy-1.25.2 paramiko-3.3.1 parsl-2023.9.11 protobuf-4.24.3 psutil-5.9.5 pyarrow-12.0.1 pyasn1-0.5.0 pyasn1-modules-0.3.0 pycparser-2.21 pyjwt-2.8.0 pynacl-1.5.0 python-dateutil-2.8.2 pyzmq-25.1.1 requests-2.31.0 rsa-4.9 s3transfer-0.6.2 setproctitle-1.3.2 six-1.16.0 tblib-2.0.0 typeguard-2.13.3 typing-extensions-4.7.1 urllib3-1.26.16

**docker image:**: [sbamin/cytotable_bug_issue102:0.0.1](https://hub.docker.com/r/sbamin/cytotable_bug_issue102)

```sh
cd /scratch
git clone https://github.com/cytomining/CytoTable.git
cd CytoTable
python
```

3. Run CytoTable `convert` function per [turorial](https://cytomining.github.io/CytoTable/tutorial.html) after giving ? a valid *source_path* argument. However, I am keeping a default ` dest_path="."` per tutorial.

```py
from cytotable import convert

# using a local path with cellprofiler csv presets
convert(
    source_path="./tests/data/cellprofiler/ExampleHuman",
    source_datatype="csv",
    dest_path=".",
    dest_datatype="parquet",
    preset="cellprofiler_csv",
)
```

>PosixPath('/scratch/CytoTable')

i.e., source_path `/scratch/CytoTable` directory (and all of its contents) are silently replaced by ? a parquet file, `/scratch/CytoTable` with md5: 219c76b59b7b2fb8fc37f5300ce50e31. I **can not recover original source path, `/scratch/CytoTable` then after.**

```sh
stat CytoTable
```

```
  File: CytoTable
  Size: 715142          Blocks: 1400       IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 409909233   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-12 23:15:48.634381429 +0000
Modify: 2023-09-12 23:15:48.684381686 +0000
Change: 2023-09-12 23:15:48.684381686 +0000
 Birth: -
```

4. Now, in the same container, if I redownload CytoTable source code and rerun `convert` function but this time with a `dest_path="testfile",` instead of default `dest_path="."`, resulting ? parquet output is now at */scratch/ctable/testfile* with an identical md5: 219c76b59b7b2fb8fc37f5300ce50e31 as above.

```sh
cd /scratch
git clone https://github.com/cytomining/CytoTable.git ctable
cd ctable
python
```

```py
from cytotable import convert

# using a local path with cellprofiler csv presets
convert(
    source_path="./tests/data/cellprofiler/ExampleHuman",
    source_datatype="csv",
    dest_path="testfile",
    dest_datatype="parquet",
    preset="cellprofiler_csv",
)
```

>PosixPath('/scratch/ctable/testfile')

file stats:

```sh
stat /scratch/ctable/testfile
```

```
  File: testfile
  Size: 715142          Blocks: 1400       IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 143427352   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-12 23:17:20.450852099 +0000
Modify: 2023-09-12 23:17:20.499852350 +0000
Change: 2023-09-12 23:17:20.499852350 +0000
 Birth: -
```

and dir stats

```sh
stat /scratch/ctable
```

```
  File: /scratch/ctable
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 143433934   Links: 9
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-12 23:17:33.613919575 +0000
Modify: 2023-09-12 23:17:20.497852340 +0000
Change: 2023-09-12 23:17:20.497852340 +0000
 Birth: -
```

**Comment by d33bs** [comment]
Thank you @sbamin for raising this issue and for the very thorough background! I plan to take a look into this and will follow up.

**Comment by d33bs** [comment]
Just an update - I wanted to provide a background and proposed solution in reference to this.

CytoTable uses `dest_path` as a "work" directory where it prepares and delivers results. When using `convert(..., join=True, ...)`(a default) this directory becomes a single parquet file at the same location. The "work" directory of the same name is removed so as to perform "cleanup". The `dest_path` is used as a preparation location in contrast with temporary storage to avoid filesystem constraints (where data prepared there may be larger than allowed) and help with potential performance issues (where data transfer from temporary locations may be time-intensive).

I can see some roads towards resolving this and would be interested in your feedback (or additional options!):

**a.** We update the tutorial to not use `.` as a `dest_path`, also expanding upon `dest_path` usage there and within the docstrings associated with the work in Python.
**b.** We do the above and update CytoTable functionality to raise an Exception on encountering `.` as a `dest_path`, avoiding the `.` scenario entirely. I wonder if the same could be said of `..` which may exhibit similar behavior.

**Comment by sbamin** [comment]
Hi Dave,

Thanks for looking into this.

>When using convert(..., join=True, ...)(a default) this directory becomes a single parquet file at the same location.

>a. We update the tutorial to not use . as a dest_path, also expanding upon dest_path usage there and within the docstrings associated with the work in Python.

My take is to avoid such default and "cleaning" operation, especially when a directory is being replaced with a file object. User may run `convert` command from a parent working directory (where .git or other core files are - like myself), or worse case, home and then point a valid `source_path` and other arguments. I am concerned that `..` could be even worse if say an user is running `convert` from `~/workdir/` or `/projects/cytotable/` and that may end up replacing a level-up directory with a parquet file. This is unusual though given a traditional `mv` command should not move an existing directory with a file object. I suggest to have similar convention and let user decide about space constraints and explicitly state risk of replacing `dest_path` with a file object.

>b. We do the above and update CytoTable functionality to raise an Exception on encountering . as a dest_path, avoiding the . scenario entirely. I wonder if the same could be said of .. which may exhibit similar behavior.

I suggest to raise exception for a `dest_path` if it is an existing directory and an user has not given an explicit `true` to let the directory (and all of recursive data) to be replaced by a parquet file.

**Comment by sbamin** [comment]
Thanks @d33bs for fixing this promptly. I will wait until you close PR and put a new version. In meantime, I will take docker image offline [sbamin/cytotable_bug_issue102:0.0.1](https://hub.docker.com/r/sbamin/cytotable_bug_issue102)

**Comment by d33bs** [comment]
Thank you again @sbamin for your help in raising this issue along with the suggested approaches. With the merge of #104 I'm going to mark this as closed. If you think we should still address other aspects here please don't hesitate to mention it and/or raise additional issues in the future. Best wishes as you move forward in your research!

**Comment by sbamin** [comment]
Wonderful and glad to be connected to you and team. Thanks and will be in touch.
