### ISSUE TITLE
NOTE: Compatibility Issue with Python 3.12 and CytoTable Due to Incompatibilities with DuckDB

### ISSUE THREAD

**Issue by axiomcura** [cytomining/CytoTable#157]
## current issues with python 3.12 
There is a compatibility issue with Python 3.12 which causes CytoTable to fail when installing. This primarily stemming from incompatibilities with DuckDB.

### Context
When trying to install CytoTable using Poetry, an error pops up saying DuckDB doesn't follow PEP 517 standards. This  prevents `CytoTable` being installed through pip, poetry and other software packages that use CyoTable as a dependency. 

Digging into the DuckDB github issue forums, there's an  [issue](https://github.com/duckdb/duckdb/issues/9301#issuecomment-1756731027) that points to incompatibilities with Python 3.12. Users are seeing similar errors and behavior when attempting to install DuckDB with Python 3.12. The forum discussion shows the DuckDB team knows about the issue and is trying to fix it by making some changes. 
- [duckdb-pr](https://github.com/duckdb/duckdb/pull/9222)

Currently, the issue remains unresolved. As a workaround, we decided to adjusting the upper limit version of Python from `<3.13` to ` <3.12`. This small change allows duckdb to be installed properly within the CytoTable's environment.

**Comment by d33bs** [comment]
An update here, I noticed that `duckdb==0.10.0` is able to succeed with installations for `python==3.12.x`. However, due to the challenges described in #163 we are not yet able to update `duckdb`. `duckdb==0.9.2` still fails with `python==3.12.x`.
