### ISSUE TITLE
Add or verify cytominer-database SQLite data source input compatibility

### ISSUE THREAD

**Issue by d33bs** [cytomining/CytoTable#18]
May have interrelationships with #5, calling this out specifically to ensure [cytominer-database](https://github.com/cytomining/cytominer-database) produced SQLite files are also compatible with pycytominer-transform.

**Comment by gwaybio** [comment]
Once we merge #46, they will be!

**Comment by d33bs** [comment]
Catching up here, closing this with the completion of #46 .
