### ISSUE TITLE
Validate output files using standardized schema

### ISSUE THREAD

**Issue by d33bs** [cytomining/CytoTable#3]
- [ ] Ensure output files are validated against standardized schema
- [ ] Include tests for validation step

**Comment by gwaybio** [comment]
This is a complicated process to include a schema, one that we probably should pursue, but will require extensive documentation. I'm closing this issue for now for cleanup, but it doesn't mean this enhancement isn't on the radar (we'll have a much more extensive issue in the future that this one won't add much too)
