### ISSUE TITLE
CytoTable logo

### ISSUE THREAD

**Issue by gwaybio** [cytomining/CytoTable#68]
Hi @vincerubinetti - would you be able to create a logo for our project, similar as you did for pycytominer in cytomining/pycytominer#196?

There is no rush! We had talked just now about adding a table in place of the pickaxe, but maybe also shifting the colors would be good? I'll leave creative flexibility up to you

**Comment by vincerubinetti** [comment]
https://github.com/cytomining/pycytominer/issues/299
