### ISSUE TITLE
Preset `cellprofiler_sqlite` uses prefixes which causes errors

### ISSUE THREAD

**Issue by jenna-tomkinson** [cytomining/CytoTable#76]
This issue was discovered in collaboration with @MattsonCam.

# Problem

When using CytoTable on SQLite files that were generated from cytomining and not CellProfiler, we had assumed we should use the `cellprofiler_sqlite` preset since I had previously [used the `cellprofiler_sqlite_pycytominer` preset for my project](https://github.com/WayScience/nf1_cellpainting_data/blob/main/3.processing_features/0.merge_sc_cytotable.ipynb) with SQLite files derived from CellProfiler.

Though, when I look directly at the [presets.py file](https://github.com/cytomining/CytoTable/blob/main/cytotable/presets.py), the only difference between the two presets is the `"CONFIG_IDENTIFYING_COLUMNS"`. 

@d33bs 
**Is there a reason for the difference? And when would this difference occur? Both presets use the `per_` prefix on the SQLite components, so I would assume there would be no difference in CellProfiler outputs.**

The main issue that we are dealing with is when using the `convert` function, we get the below IOError and BinderException:

![image](https://github.com/cytomining/CytoTable/assets/107513215/afb39187-a70c-450b-9eee-2dd1f8dee940)

![image](https://github.com/cytomining/CytoTable/assets/107513215/d990f7b2-f6d0-43bd-9694-b09d8fe302ff)

# Solution

To get around the first error, we decided to change the preset manually to remove all of the `per_` prefixes:

```python
"CONFIG_JOINS": """
            WITH Image_Filtered AS (
                SELECT
                    Metadata_ImageNumber,
                    Image_Metadata_Well,
                    Image_Metadata_Plate,
                    Image_Metadata_Site
                FROM
                    read_parquet('image.parquet')
                )
            SELECT
                *
            FROM
                Image_Filtered AS image
            LEFT JOIN read_parquet('cytoplasm.parquet') AS cytoplasm ON
                cytoplasm.Metadata_ImageNumber = image.Metadata_ImageNumber
            LEFT JOIN read_parquet('cells.parquet') AS cells ON
                cells.Metadata_ImageNumber = cytoplasm.Metadata_ImageNumber
                AND cells.Cells_Number_Object_Number = cytoplasm.Cytoplasm_Parent_Cells
            LEFT JOIN read_parquet('nuclei.parquet') AS nuclei ON
                nuclei.Metadata_ImageNumber = cytoplasm.Metadata_ImageNumber
                AND nuclei.Nuclei_Number_Object_Number = cytoplasm.Cytoplasm_Parent_Nuclei
            """
```
This worked and we then received the new error which is the BinderException. To solve this, we had to remove the "Image_" prefix from the `Image_Filtered` variable as seen below:

```python
WITH Image_Filtered AS (
                SELECT
                    Metadata_ImageNumber,
                    Metadata_Well,
                    Metadata_Plate,
                    Metadata_Site
                FROM
                    read_parquet('image.parquet')
                )
```

# Need for a PR

What we will need based on this issue is a dedicated preset for SQLite outputs directly from cytomining that will not contain any of the prefixes that SQLite files directly outputted from CellProfiler have.

**But we need to have this code work before that PR, so I will keep this issue open and updated until we have gotten it to work.**

**Comment by jenna-tomkinson** [comment]
# Current errors and stopping point

We started getting more BinderExceptions after what we did above:

![image](https://github.com/cytomining/CytoTable/assets/107513215/88e21f30-9d22-4a60-ac13-a7fda007a604)

![image](https://github.com/cytomining/CytoTable/assets/107513215/bff53c8b-d3ba-40b6-9943-3f5b4edfaf7e)

After attempting to update the presets to get around the errors (e.g., adding and removing prefixes), we came to a final error we could not get around/had no solution for:

![image](https://github.com/cytomining/CytoTable/assets/107513215/53705fdc-61ce-43d8-aa57-e1b18462e2f8)

This error doesn't make a lot of sense to us and doesn't give us an idea on how to fix it.

# Convert function

For reference, here is the exact `convert` function and parameters we used:

```python
convert(
    source_path=f"./big_drive/data/{row['plate']}.sqlite",
    dest_path=f"./big_drive/cytotable_data/{row['plate']}",
    dest_datatype="parquet",
    chunk_size=150000,
    parsl_config=parsl_config,
    preset=preset,
)
```

**Comment by gwaybio** [comment]
based on conversation with @d33bs this afternoon, we can close this issue once we merge #46. @d33bs took a look at this PR already and anticipates that it will be quick. He is going to take on the development, and can close this issue once resolved!

**Comment by d33bs** [comment]
Catching up here, closing this out as I believe this is now resolved. If not, please don't hesitate to reopen or open a new issue to discuss! Thanks again @jenna-tomkinson and @MattsonCam for your help in resolving this!
